# Generated by Django 3.2.8 on 2021-12-14 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='email',
            table='email',
        ),
    ]
