# Generated by Django 3.2.8 on 2021-12-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_accountactivationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountactivationcode',
            name='user',
        ),
        migrations.AddField(
            model_name='accountactivationcode',
            name='email',
            field=models.EmailField(default='fixerex@gmail.com', max_length=255),
            preserve_default=False,
        ),
    ]
