# Generated by Django 3.2.8 on 2021-12-15 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211215_0639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountactivationcode',
            old_name='code',
            new_name='verification_code',
        ),
    ]
